### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by cyrusmsk** [rillki/tiny-grad#1]
Hi,

maybe you will consider changing naming)
And also repos for inspirations:
https://github.com/karpathy/micrograd
https://github.com/tinygrad/teenygrad
https://github.com/tinygrad/tinygrad

**Comment by rillki** [comment]
@cyrusmsk Thanks for the links! 

As for renaming the repo, I need to think about this. But why do you suggest it should be renamed?

**Comment by cyrusmsk** [comment]
The last link is tinygrad project, which is already kinda popular. And current name could be confusing for users..

**Comment by rillki** [comment]
Renamed to `tiny-autodiff`, since it implements simple auto-differentiation. I like the name better.

**Comment by sginiatulin** [comment]
If compare this library with grain does it have more functions supported?
Could the library be incorporated into grain?
